### ISSUE TITLE
annotationProcessor in build.gradle not working, apt does

### ISSUE THREAD

**Issue by GoltsevEugene** [JakeWharton/butterknife#1066]
Hi Jake!
If I put in dependencies next:
```
compile 'com.jakewharton:butterknife:8.8.1'
annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
```
It does not work - gives NPE on first view binded.

If I replace it with:
```
compile 'com.jakewharton:butterknife:8.8.1'
apt 'com.jakewharton:butterknife-compiler:8.8.1'
```
it works well.
Am I do something wrong?

**Comment by JakeWharton** [comment]
Your build is pulling in the legacy android-apt plugin either directly or transitively through some other plugin. This hasn't been needed as of the Android Gradle plugin 2.2 and you should figure out which plugin is pulling it in and upgrade it so that you can use the built-in `annotationProcessor` configuration.
