### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by pirupius** [JakeWharton/butterknife#1112]
Was checking for the latest version so i could update my dependencies and found 

    dependencies {
        compile 'com.jakewharton:butterknife:8.8.1'
        annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    }

as opposed to the `apt 'com.jakewharton:butterknife-compiler:8.8.1'` in android studio 2.3.3. Suddenly I was getting NullPointerExceptions and had to spend some time looking at my code if at all i had made a mistake with any references but all was fine. But when i reverted  to using `apt` instead of `annotationProcessor ` everything starting working as normal. 

Is this a configuration issue with android studio or something else? cause i did some digging trying to see if i there's a configuration i missed

**Comment by JakeWharton** [comment]
You have another plugin which is adding the `android-apt` plugin which is disabling the built-in annotation processor support. You can discover it by running `./gadlew buildEnvironment`. The `android-apt` plugin hasn't been needed since Android Gradle Plugin 2.2.0 or newer and the built-in `annotationProcessor` should be used instead.
