### ISSUE TITLE
android.support.annotation.Nullable and butterknife-reflect

### ISSUE THREAD

**Issue by egor-n** [JakeWharton/butterknife#1364]
The `android.support.annotation.Nullable` annotation has `CLASS` retention policy and butterknife-reflect doesn't see them at runtime.

Is there any way to circumvent this problem without changing all annotations to `javax.annotation.Nullable`?

**Comment by JakeWharton** [comment]
Unfortunately not. You have to use an annotation with runtime retention. You could try filing a bug on the AndroidX component to see if you can convince them to change the nullability annotations to runtime retention.

**Comment by AndiMiko** [comment]
makes Butterknife-reflect unusable. Please add support for incremental annotation processing.

**Comment by JakeWharton** [comment]
As you'll see in the release notes, this restriction was removed in 10.1.0.

**Comment by AndiMiko** [comment]
Thanks Jake, I'll take a look.

Nonetheless, this pretty much illustrates why it is a bad idea to use different code in dev rather than in production. I was skeptical before, but now I think we'd rather not have incremental compilation.

It would be much more helpful if you'd make the annotation processor compatible for incremental builds. (As suggested in the linked issue)

**Comment by JakeWharton** [comment]
Except it doesn't because both code bases are tested using the same test
suite ensuring consistency in behavior.

**Comment by AndiMiko** [comment]
Yes, but even good test coverage won't prevent bugs from happening, just like this one, which took me a bit to investigate. Don't see what justifies this risk.

Could you give a reasoning why you wouldn't just enable incremental builds on the annotation processor just like the fork https://github.com/stephanenicolas/butterknife/tree/sni/version-10-incap did? You can make it optional like dagger.

If you explain it I might be convinced, but right now it appears that you just don't want to make the work that was put into butterknife-reflect obsolete.

**Comment by JakeWharton** [comment]
That statement is true of all literally all bugs so it's not an argument
one way or the other.

I'm making annotation processors obsolete in dev builds which winds up
being faster. Faster is better.

**Comment by AndiMiko** [comment]
It's not true for all bugs. This is specific to using different code on dev instead of release. This might cause issues where developers don't have/notice bugs that gets shipped in production.

You are referring to the build time, correct? Runtime is slower with reflect if I understand correctly? (That's fine for dev builds)

To be fair I didn't really notice the build time improvement with butterknife-reflect. Incremental compilation is much more significant. I think it feels a bit odd that you refuse to make a simple change to conform with incremental compilation even though @stephanenicolas demonstrated it is possible.

Will probably have to go with the fork for now, which feels quite odd ...

**Comment by JakeWharton** [comment]
Let's say incremental compilation saves 99% of the time spent in the
annotation processor. The reflect runtime saves 100% of time.

Oh and it also always saves 100% of the time regardless of whether your
other annotation processors are incremental. Or if you're using kapt where
incrementality doesn't even exist. Or if you're not using Gradle as your
build system.

If you prefer that your use of this library always impacts your development
build speeds then you're welcome to use the fork and incremental annotation
processing. I will be pushing for the solution which produces faster builds
though.

**Comment by AndiMiko** [comment]
Well after our discussion and your self-opinionated views I decided to give Butterknife-reflect another try, just to find out that now I get crashes in reflect somewhere else (for unknown reasons that I refuse to waste more time on). Here is the relevant stacktrace in case it helps:
```
     Caused by: java.lang.ClassCastException: libcore.reflect.ParameterizedTypeImpl cannot be cast to java.lang.Class
        at butterknife.ButterKnife.parseBindViews(ButterKnife.java:282)
        at butterknife.ButterKnife.bind(ButterKnife.java:152)
```
By now BK-reflect lost me more time than it could ever save my team. I think it is outrageous that you decide to purposely not activate incremental builds on the annotation processor just to push your reflect agenda. Your arguments MAY be valid, but you let it appear as if it is black or white, when in fact you could just let the developer decide themselves what they think is appropriate to use.

Disappointed.

**Comment by JakeWharton** [comment]
File a bug
