### ISSUE TITLE
Static interface methods are only supported starting with Android N (--min-api 24):

### ISSUE THREAD

**Issue by devmike01** [JakeWharton/butterknife#1416]
I'm having this issues when I try to use the latest ButterKnife library in my project. I tried many difference solution to no avail. But after removing Butterknife, it works and I was able to build my project successfully.

```
Static interface methods are only supported starting with Android N (--min-api 24): void butterknife.Unbinder.lambda$static$0() |  
Invoke-customs are only supported starting with Android O (--min-api 26) |  
null |  
com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\***\.gradle\caches\transforms-1\files-1.1\butterknife-runtime-9.0.0-rc2.aar\6ce172ce87edce90d1ef858835ddb42a\jars\classes.jar |  
com.android.builder.dexing.DexArchiveBuilderException: Error while dexing. |  
com.android.tools.r8.CompilationFailedException: Compilation failed to complete |  
com.android.tools.r8.utils.AbortException |  


```

**Comment by JakeWharton** [comment]
Per the release notes, all artifacts are now built with Java 8 and reauire you to use Java 8 on the consuming side.

**Comment by TWiStErRob** [comment]
@JakeWharton so does this mean that even though we're not using Java 8 (we use Java 7 + Kotlin JDK7, minApi 21), we'll need to add a desugaring step (which takes minutes), if we want to continue using Butterknife?

**Comment by JakeWharton** [comment]
Desugaring lives inside D8 as of AGP 3.2 and newer and it does not take
minutes. In fact, D8 with desugaring is faster than dx without desugaring.

Otherwise yes!

**Comment by TWiStErRob** [comment]
Hmm, that sounds promising, thanks!

**Comment by kyay** [comment]
@TWiStErRob read this article right here: https://developer.android.com/studio/write/java8-support
I had the exact same problem because I didn't know about the new changes in the Android Gradle Plugin like desugaring of Java 8 features.
Look especially at the section where it says "To start using supported Java 8 language features..."

**Comment by TWiStErRob** [comment]
@kyay yes, I saw that page previously, but note "Figure 1" showing a separate desugar step. That means a separate Gradle task, and when we previously enabled it, there was one, which took minutes to run on our project (without using any Java 8 specifics, just Java 7 compiled as 8). But as Jake said, there's no such task any more, desugar is part of dex transform in D8 now. Still seems to slow down a tiny bit, but not significant.

Btw, a sidenote: I only changed target to Java 8, source stayed Java 7, because there's no point making effort to use Java 8 features, while we're migrating to Kotlin anyway.

**Comment by alexsxander** [comment]
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

**Comment by Satria7** [comment]
just add this to build.gradle

compileOptions {
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
}

**Comment by Jefh15** [comment]
![image](https://user-images.githubusercontent.com/31804499/76712141-6107e600-66db-11ea-8464-f0295df92cf5.png)

**Comment by gema20hd** [comment]
Jefh15 si me funcionó. Gracias

**Comment by rmogusu** [comment]
compileOptions {
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
}
it worked for me Thanks guys

**Comment by Alvinkariuki** [comment]
Works great thanks
