### ISSUE TITLE
Using OnClick with Listener Binding

### ISSUE THREAD

**Issue by SivaramSS** [JakeWharton/butterknife#1569]
Hi,
I have declared my data in the layout file as follows. I'm trying to pass data object to my ClickHandler method.
 
`<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <data>
        <variable
            name="data"
            type="com.siva.sample.Data" />
    </data>

    <View android:id="@+id/myClickView"
             ...
             android:onClick="@{()->ClickHandler.handleViewClick(data)}" />
</layout>
`
The problem with above approach is that, i have to repeat this onClick code for different configuration (landscape, sw600 etc). Instead a one time assigning would help me a lot. I'm expecting to do something like this.

`@OnClick(R.id.myClickView) ////get data object here
public static void handleViewClick(Data data) {
    ...
}`

Is it possible to achieve this somehow?

**Comment by JakeWharton** [comment]
Butter Knife is just a convenience around calling `setOnClickListener` on a view reference. It doesn't know anything about whether or not your layout is using data binding or not nor how to access things like your data objects. But more importantly, it doesn't have any way of knowing these things because of how it works.

What you describe is just a flaw of data binding in how it operates in the resource system of Android. It should be solved by Jetpack Compose, although that's a ways off...
