### ISSUE TITLE
Adding butterknife in Android.mk file failed

### ISSUE THREAD

**Issue by thejaswimarakini** [JakeWharton/butterknife#1573]
Hi, 

I am trying to add butterknife dependency for one of my system app. To do this I have added the dependency in Android.mk file as below, 

**LOCAL_STATIC_ANDROID_LIBRARIES += \
    android-support-constraint-layout \
	androidx.appcompat_appcompat \
	com.jakewharton:butterknife \
	com.jakewharton:butterknife-compiler**

But then I am unable to compile and build my project. I am getting something like **target pattern doesn't match ..** 

Am I missing anything here?

**Comment by JakeWharton** [comment]
I have no experience with .mk files. The compiler should be added to the `-processorpath` for javac whereas the butterknife artifact gets added to the regular classpath. As to how to set up targets and such so that it all works, you'll have to ask on a forum more appropriate for getting help with .mk files. Perhaps that's StackOverflow?
