### ISSUE TITLE
9.0.0-SNAPSHOT  is missing from sonatype

### ISSUE THREAD

**Issue by marksalpeter** [JakeWharton/butterknife#1594]
Hi! Our project is broken at the moment because someone delete the `9.0.0-SNAPSHOT` from the sonatype repo. 

You can see [here](https://oss.sonatype.org/content/repositories/snapshots/com/jakewharton/butterknife-gradle-plugin/maven-metadata.xml) that theres still a `9.0.0-SNAPSHOT` reference in the meta data and that there was a botched update yesterday, 03/15/2020 @ 11:21pm (UTC), that must have deleted the directory accidentally. You can verify for yourself that there is no corresponding 9.0.0 directory [here](https://oss.sonatype.org/content/repositories/snapshots/com/jakewharton/butterknife-gradle-plugin/).

I'm going to try the 10.2.2 upgrade again because of the missing files, but we've been having trouble with it. If someone could please put that version back it would be greatly appreciated. Thanks!

**Comment by JakeWharton** [comment]
Snapshots have no guarantees for how long they live. Historically, Sonatype has deleted snapshots as soon as the associated release version was published. I'm shocked that a 9.0.0-SNAPSHOT lived this long. It really shouldn't have.

> I'm going to try the 10.2.2 upgrade again because of the missing files

What kept you on a snapshot instead of just using 9.0.0 release version?

> You can see here that theres still a 9.0.0-SNAPSHOT reference in the meta data

For the broken metadata you can create a ticket on Sonatype's issue tracker about it: https://issues.sonatype.org/. Sounds like their script which culls old snapshots should probably also update the metadata? Although I'm not sure whether it creates a problem in practice or not.

> If someone could please put that version back it would be greatly appreciated. 

It's basically impossible to know what commit the artifacts came from. It might be the one immediately prior to the 9.0.0 release or it might not have been. Usually they're pushed automatically by CI based on whatever is the latest on master. Snapshots are published for testing purposes only. You should not be relying on them longer than to verify a bug fix. I would advise moving to 9.0.0 immediately which should be nearly identical to whatever the 9.0.0-SNAPSHOT was before attempting to upgrade.

**Comment by marksalpeter** [comment]
Just switched our gradle to point to the 9.0.0 release, worked like a charm. Thanks @JakeWharton.
