### ISSUE TITLE
Is there incremental feature version that depend on android support v28

### ISSUE THREAD

**Issue by Tan-Tshunglee** [JakeWharton/butterknife#1644]
For the compatibility reasons, My SDK library project can not upgrade to android x library.  So the version of butter knife I used stuck at v9.0.  But I  really need the incremental compilation feature introduced by new version butterknife.
  Is there such version ? I wish it would be yes. :)

**Comment by JakeWharton** [comment]
It is not supported, no. Incremental annotation processing is a performance optimization. You should never _need_ it.

If you want to implement incremental annotation processing on top of 9.x you will need to fork the project. Otherwise, consider moving to view binding or just using findViewById to bind your UI.
