### ISSUE TITLE
How to be compatible with jetpack viewbinding in the butterknife project

### ISSUE THREAD

**Issue by ZhouBey** [JakeWharton/butterknife#1651]
Now,my project in production is using butterknife,i want to use viewbinding in new activity or fragment,so the question is that how do I avoid those activities that have used butterknife to generate binding classes,it will increase the size of the apk package.If the butterknife is completely removed, or manually add "tools:viewBindingIgnore="true" in activities used kutterknife,work will become complicated.Please give me some advice.

**Comment by JakeWharton** [comment]
R8 will remove unused view binding classes. Butter Knife only generates code based on annotations. So there's really nothing to do here. If you enable view binding your app will not grow. As you start using view binding instead of Butter Knife those view binding classes will be kept and Butter Knife will generate less.
