### ISSUE TITLE
Generate custom binders/injectors vs. generic ButterKnife.inject()

### ISSUE THREAD

**Issue by cgruber** [JakeWharton/butterknife#197]
The current ButterKnife.inject() currently is generalized, but in the spirit of Dagger 2, could be made to simply generate a per-bindable-type binder.  For instance (using the proposed naming in #196), it could generate binders along this line: 

```
class MyActivity extends Activity {
  @BindView(R.id.title) TextView title;

  @Override public void onCreate(Bundle savedInstanceState) {
     super.onCreate(savedInstanceState);
     setContentView(R.layout.simple_activity);
     MyActivity_Views.bind(MyActivity activity);
     // TODO Use "injected" views...
  }
}
```

In this respect, it would act similarly to `@Component` or `@AutoValue` creating a very simple entry point which can then be immediately consumed.

Non-activities would work similarly:

```
public class FancyFragment extends Fragment {
  @BindView(R.id.button1) Button button1;

  @Override View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    View view = inflater.inflate(R.layout.fancy_fragment, container, false);
    FancyFragment_Views.bind(FancyFragment activity).to(view);
    // TODO Use "injected" views...
    return view;
  }
}
```

**Comment by jasta** [comment]
@JakeWharton I'm also interested in this.  Though I agree the practical benefit for small apps is virtually 0, it is actually a problem of scale.  For instance, `ButterKnife#bind` maintains a linked hash map which is notoriously slow on Android and allocates an extra object for each entry plus one extra object for the viewbinder instance that is created.  If you modularize your code to an extreme, this could end up generating thousands of objects unnecessarily that are persistently pinned in the heap.  Since Dalvik's GC is linear, this just has a constant drag on app performance for the entire process lifetime.  And that's ignoring the relative performance loss of moving to invoke-virtual from invoke-direct/static.

The proposal made by @jnlopar looks like a great compromise to me, in particular simplifying the generated $$ViewBinder bind method and using an _ to denote that it is expected to be used as a public API.  Documentation can be used to steer folks toward the `ButterKnife#bind` API for common users all the same.

This does however leave an issue with manually passing in the `Finder`.  An alternative, but not a good one, would be to autogenerated many `bind` methods for each `$$ViewBinder` with the signatures separated out.  Proguard would then be relied upon to strip out all the extra methods, though this would cause a lot more practical problems for smaller developers that might be near the method dex limit already for debug builds.

Perhaps an alternative is to take a hint from Google's recent databinding effort which autogenerates application global classes in addition to intermediate ones which are used to address all the intermediately generated code.  That is, imagine instead of using reflection or even object instances for your view binders, you generated a giant class to trampoline from:
```java
class ButterKnifeBinder {
  public static void bind(Finder finder, Object target, Object source) {
    switch (target.getClass().getName()) {
      case "com.myapp.MyActivity":
        com.myapp.MyActivity$$ViewBinder.bind(finder, (com.myapp.MyActivity)target, source);
        break;
      ...
    }
  }
```
This requires java7 as written but can easily be manually converted to java6 compatibility with:
```java
  switch (className.hashCode()) {
    case 0x<precomputed>:
      if ("com.myapp.MyActivity".equals(className)) { ... }
    ...
  }
```
This is a very powerful way to implement your own more efficient instruction forwarding mechanism than using truly dynamic reflection and map data structures.  BTW, I've caliper benchmarked this at high scale (n > 1000) on other projects and have found that it is hundreds of times faster to do this trampoline style than to generate the map.  One gotcha you will run into at very high scale though is that there is a concrete instruction count limit on both Dalvik and ART which disables a large number of optimizations if reached.  To work around this, the code generation has to get smarter and shard into multiple smaller functions.  This is actually easily done using something like:
```java
  switch (hashCode & 0xf) {
    case 0x0: ...
    case 0x1: ...
    case 0x2: ...
    ...
  }
```

**Comment by JakeWharton** [comment]
This is mostly done for the next release, but won't be considered API stable until 9.0.
