### ISSUE TITLE
butterknife + data binding

### ISSUE THREAD

**Issue by schwiz** [JakeWharton/butterknife#269]
No actual issue here, I was just curious to know what your plans are if any in regards to databinding with butterknife. They don't do exactly the same thing but they are similar and I think they could possibly work well together. I don't have any suggestions for api additions or anything at this time.

**Comment by JakeWharton** [comment]
No plans. The data binding might be useful in the most trivial cases, but there was no innovation done so it'll be equally as painful as similar solutions on other platforms when complexity increases (e.g., XAML). This library scales to the advanced cases since it forces you to keep binding logic in code where it more correctly belongs.
