### ISSUE TITLE
Injectors not generated in dependent modules.

### ISSUE THREAD

**Issue by Diolor** [JakeWharton/butterknife#276]
Related to #251 .

If Butterknife is a dependency in the base module it will give access to its API other modules but will not generate any view injectors on the dependent modules.

Not critical, so if not fixed would be good to exist as a warning somewhere in the docs.

**Comment by JakeWharton** [comment]
This is not true. The presence of the dependency means that the annotation processor will run for all downstream projects since the library is on the classpath. Granted, you have to be using the annotations for the processor to run. It's not just going to run on subclasses, for example, but it doesn't have to since it also walks the class hierarchy to find the generated binder.

Do you have an example demonstrating this not working?

**Comment by Diolor** [comment]
Hmm indeed.

I use it with dagger 2 but normally shouldn't be any problem on that. 

Will close the issue and report again when be sure that it's bkniffe's issue.
