### ISSUE TITLE
Bind not work on Genymotion with Android 4.1.1

### ISSUE THREAD

**Issue by askarsyzdykov** [JakeWharton/butterknife#311]
Perfect Worked in Android 5.1.1
on Android 4.1.1 viewRoot is null.
on Samsung tablet with 4.4.2 It does not work

compile 'com.jakewharton:butterknife:7.0.1'

<code>
@Bind(R.id.root)
    View viewRoot;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash);
        ButterKnife.setDebug(true);
        ButterKnife.bind(this);
        int padding = getResources().getDimensionPixelSize(R.dimen.activity_generic_margin);
        viewRoot.setPadding(padding, getStatusBarHeight(), padding, padding);
    }
</code>

proguard:
<code>
-keep class butterknife.** { *; }
-dontwarn butterknife.internal.**
-keep class **$$ViewBinder { *; }
-keepclasseswithmembernames class * {
    @butterknife.* <fields>;
}
-keepclasseswithmembernames class * {
    @butterknife.* <methods>;
}
</code>

logs:
Looking up view binder for app.logistic.kz.logistic.activities.SplashActivity
Not found. Trying superclass android.app.Activity
MISS: Reached framework class. Abandoning search.

**Comment by artem-zinnatullin** [comment]
I guess it's multidex problem, some (at least those that were generated by
ButterKnife) of your classes were placed in another dex file because you
had exceeded 65k methods limit and on Android 4 you didn't load other dex
files.

Please check the documentation about multidex.
13 июля 2015 г. 8:51 AM пользователь "Askar" <notifications@github.com>
написал:

**Comment by askarsyzdykov** [comment]
I forgot to add the inheritance
<code>
public class MyApplication extends MultiDexApplication{
...
}
</code>

Thanks, Artem.
