### ISSUE TITLE
7.0.1 issues

### ISSUE THREAD

**Issue by chenhonggy** [JakeWharton/butterknife#322]
Logcat :
Error:Execution failed for task ':app:compileDebugJava'.
> java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$MethodSymbol cannot be cast to javax.lang.model.element.TypeElement
l><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)</li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

7.0.1  I got this problem

**Comment by JakeWharton** [comment]
This doesn't really tell me anything, but it's happening because you have a syntax error in your code somewhere that's causing ButterKnife to fail. Once I get around to #195 (which requires #192 first) this won't throw a nasty exception.

If you have a full stack trace or reproducible sample I can take a look, otherwise just go looking for a syntax error near a Butter Knife annotation.
