### ISSUE TITLE
Using library in FragmentTabHost with EventBus

### ISSUE THREAD

**Issue by sduqlsc** [JakeWharton/butterknife#421]
I have 4 fragments added into FragmentTabHost activity and some functions in tabs need to login —— 'LoginActivity' in which when login succeed, eventbus would post login success event into 4 tab fragments, so here is the problem:

In the onEvent method, the widget controls are null, i can see why—— when tab changes, the onDestroyView and ButterKnife.unbind  is called while eventbus is registered onCreate and ubind in onDestroy. So any ideas to solve this issue?

Thanks!

**Comment by JakeWharton** [comment]
This problem has nothing to do with ButterKnife specifically–it just happens to be used in your app. I highly suggest posting more general usage questions like this to StackOverflow or the Android developer mailing list. Since it's not strictly a ButterKnife feature or bug, you're unlikely to find a lot of people watching this space and offering help.
