### ISSUE TITLE
in activity use View.performClick invalid

### ISSUE THREAD

**Issue by alicemmm** [JakeWharton/butterknife#424]
@Bind(R.id.about_list_rl_01)
    RelativeLayout relativeLayout;

 @OnClick(R.id.about_list_rl_01)
    void onClickWelcome() {
      Log.e(TAG,"onClickWelcome");
    }

@onclick(R.id.about_back)
void onClickBack(){
 relativeLayout.performClick() 
}
when I click back button ,it should to show log "onClickWelcome" ,but not. if I use 

relativeLayout.setOnClickListener(){
   void onClick(){
  Log.e(TAG,"onClickWelcome");
}
}

it is ok. I don't know how to do it.

**Comment by JakeWharton** [comment]
Paste the full exeption.

**Comment by HappyDr0id** [comment]
I actually have the same problem.

For some reason, I have to programmatically click on a button. I call the View.performClick method, I expect the code inside my @OnClick method to be executed but it is not the case. On the contrary if I manually set an OnClickListener on the button (and remove the @OnClick method), the code is executed as expected. So I suppose that there could be a problem of compatibility with the View.performClick method and the way Butterknife is adding an OnClickListener on the view.

Thank you in advance if you can find an explanation to this problem.

**Comment by timqi** [comment]
Do you really call the ButterKnife.bind(...)  before performClick()?

**Comment by alicemmm** [comment]
Yes .it should be nullpointExection if I do not call ButterKnife.bind(...)

**Comment by mgwizdala91** [comment]
I encountered a similar problem. Code generated by @OnClick uses DebouncingOnClickListener. It's documentation says
`static boolean enabled = true;`
DebouncingOnClickListener will perform your callback only if enabled is equal true
Which will be setted to fales if any of your binded views has been clicked. Since inside this view you are programatically calling

**Comment by mgwizdala91** [comment]
I have encountered a similar problem. Code generated by @OnClick uses DebouncingOnClickListener which "debounces multiple clicks posted in the same frame. A click on one button disables all other callbacks. 
Problem appeard because you were trying to chain clicks before DebouncingOnClickListener enables himself
