### ISSUE TITLE
Use AppCompatResources#getDrawable() under the hood

### ISSUE THREAD

**Issue by ZacSweers** [JakeWharton/butterknife#460]
Originally was here for requesting vector drawable support, but we can actually just use this method under the hood and support all variants in `@BindDrawable`

**Comment by hzsweers** [comment]
Would presumably look like:

```java
@BindVector(R.drawable.thing) AnimatedVectorDrawable thing;
```

Where the type could be inferred from the field type (allowing the annotation to work on any of the four permutations).

To kind of expand from this a bit, I've been wondering if `BindDrawable` should do this in general, where you can use it on any drawable and have it cast accordingly. Compat vectors would require special implementations though since they have separate creators.

**Comment by hzsweers** [comment]
For anyone interested, I have a branch with this done: https://github.com/hzsweers/butterknife/tree/z/vector

**Comment by consp1racy** [comment]
Sticking to `BindDrawable` would be nice since it looks like AppCompat is able to support inflating anything even custom drawables.

And https://github.com/JakeWharton/butterknife/issues/461 of course.

**Comment by hzsweers** [comment]
That's not feasible for support vector drawables since they require manual creation through the create() APIs. Animated vector drawables also have extra APIs over the usual drawable APIs that most people would want to use.

**Comment by JakeWharton** [comment]
Seems like we can do this with `@BindDrawable` now

**Comment by hzsweers** [comment]
Yeah with `AppCompatResources#getDrawable()`. I'll edit the title/description :)

**Comment by tyler-at-uv** [comment]
I would like to up vote this issue - trying to use binding for VectorDrawableCompat. Thank you.
