### ISSUE TITLE
Proposal: Resolved Attributes support

### ISSUE THREAD

**Issue by ZacSweers** [JakeWharton/butterknife#461]
Been mulling over this for my Barber library, but wondering if this something that would be better suited to Butter Knife given its more general use case. The idea would be this:

``` java
@BindAttr(R.attr.colorPrimary) @ColorInt int primaryColor;

// And would generate code like this
TypedValue outValue = new TypedValue();
context.getTheme().resolveAttribute(R.attr.colorPrimary, outValue, true);
target.primaryColor = outValue.data;
```

Could possibly reuse a `TypedValue` instance as well.

**Comment by hzsweers** [comment]
Corresponding issue I opened about this awhile back: https://github.com/hzsweers/barber/issues/15

**Comment by TheKeeperOfPie** [comment]
This would definitely be helpful, as it makes switching themes a lot easier. Also, we could have a generic `@BindAttr` without the need for specifying the resource because `TypedValue` provides a `type` field which can be used to determine the resource/variable type.

Actually, I think it's possible to completely generalize the reference through `Resources. getResourceTypeName(int id)`, so it's technically possible to `@Bind(R.id.anything) Class name`.

```
@BindAttr(R.attr.colorPrimary) int primaryColor;

TypedValue value = new TypedValue();
context.getTheme().resolveAttribute(R.attr.colorPrimary, value, true);
switch (value.type) {
    case TYPE_INT_COLOR_ARGB4:
        ...
    case TYPE_STRING:
        ...
}
```

**Comment by kageiit** [comment]
> context.getTheme().resolveAttribute(R.attr.colorPrimary, outValue, true);

#613 would give you this for free

**Comment by consp1racy** [comment]
How do you determine which context to use? My Toolbar will have a different theme than my Activity. Named annotation parameter set to a view ID?

**Comment by TheKeeperOfPie** [comment]
Well, logically it would inflate with the form of Context which you pass to ButterKnife.bind(). I don't think you should be expecting a theme attribute inside a Context whose theme is different from where you bind the attribute. I feel like in that example, you'd want to bind the attribute inside the Toolbar, or well I guess a subclass, so that you access the correct Context.

**Comment by consp1racy** [comment]
1) We're all on the same board concerning the default behavior.

2) Like hell am I going to subclass Toolbar to inflate drawables for a menu which is completely decoupled. That's why I suggested an annotation parameter.

**Comment by JakeWharton** [comment]
We'll be using the context that's passed in directly or the one inferred from the view which is passed in.

**Comment by dstocking-ext** [comment]
+1 It pains me to admit that I just figured out how themes and styles work. I went to do this with butterknife and couldn't. I so wish I could. Good to know its at least going to be made.

Is anyone working on this right now? It doesn't look like it, but it doesn't look like anyones working on 9.0 stuff so idk.
