### ISSUE TITLE
Unbind TextWatcher

### ISSUE THREAD

**Issue by vadims** [JakeWharton/butterknife#521]
Unbind should call `removeTextChangedListener(listener)` instead of `addTextChangedListener(null)`.

https://github.com/JakeWharton/butterknife/blob/1bc7bc1dab9c633afd4dbd49c5cc18cb16043bd7/butterknife-compiler/src/test/java/butterknife/OnTextChangedTest.java#L76

**Comment by JakeWharton** [comment]
Yep. Good catch.

**Comment by PrathameshKesarkar** [comment]
@JakeWharton  where is unbind in 8.0,1

**Comment by JakeWharton** [comment]
In the change log.

**Comment by PrathameshKesarkar** [comment]
thanks found it Btw I was using 7.0.1 
and it was giving me this working while building release version of my app
Warning: butterknife.internal.InjectViewProcessor: can't find superclass or interface javax.annotation.processing.AbstractProcessor

is this fixed in 8.0.1 like do I still need to specify something in my proguard

**Comment by JakeWharton** [comment]
No you do not
