### ISSUE TITLE
progurad/obfuscating not work right

### ISSUE THREAD

**Issue by alexwang3322** [JakeWharton/butterknife#561]
version:  buttetknife-7.0.1
 same question see:  #104  , #197  , #409 
 description:
 all the solutions I had been tried. but they are all not working with right obfuscation apk.
_1.if I write nothing in proguard.txt about butterknife, then it will work but obfuscate nothing.
2.if I write butterknife proguard-rule.txt into my progurad.txt, then it will work but obfuscate nothing too.
3.if I write things same as #104 solution, it will carsh with nullpointexception,I think it means butterknife didn't make runtime find the right file._

**Comment by JakeWharton** [comment]
Here's the rules for v8 which you can probably adapt to v7:
```

# Retain generated class which implement ViewBinder.
-keep public class * implements butterknife.internal.ViewBinder { public <init>(); }

# Prevent obfuscation of types which use ButterKnife annotations since the simple name
# is used to reflectively look up the generated ViewBinder.
-keep class butterknife.*
-keepclasseswithmembernames class * { @butterknife.* <methods>; }
-keepclasseswithmembernames class * { @butterknife.* <fields>; }
```

**Comment by filipedelimabrito** [comment]
@JakeWharton Do you consider add the rules in [README.md] (https://github.com/JakeWharton/butterknife/blob/master/README.md) a good idea? 
I say it because I notice that some people are looking for these correct rules and I think that the README.md file is a good place to add it (or then, on the [ButterKnife website](https://jakewharton.github.io/butterknife/)). 

Related issue is: https://github.com/JakeWharton/butterknife/issues/409

Thanks for this great library!

**Comment by JakeWharton** [comment]
Rules are not needed with v8.0

**Comment by filipedelimabrito** [comment]
Really!  

> "ProGuard rules now ship inside of the library and are included automatically."

https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md#version-800-2016-04-25

I didn't see the Changelog. Sorry!

Thanks again!
