### ISSUE TITLE
NullPointerException  on buildToolsVersion 24.0.0 rc4

### ISSUE THREAD

**Issue by smallobserver** [JakeWharton/butterknife#616]
i use ButterKnife 7.0.1  ,when I change buildToolsVersion to 24.0.0 rc4   it can't use. but i use some grammar in java8  so I can't change the buildToolsVersion

**Comment by zubietaroberto** [comment]
Butterknife does not work with the Jack compiler (Required for compiling with build tools 24). Currently looking for a workaround.

**Comment by JakeWharton** [comment]
Jack is not required for using build tools 24.

**Comment by jaredsburrows** [comment]
@smallobserver Try using this with build tools `24.0.0` now.

**Comment by JakeWharton** [comment]
> Butterknife does not work with the Jack compiler

This is not true. Replace `apt` with `annotationProcessor`.

**Comment by zubietaroberto** [comment]
@JakeWharton Finally figured it out. It DOES work. But not in with the "stable" build tools. You need the gradle 2.2.0 alpha3 build tools. I couldn't get it working before because I try to keep to stable branches for most projects.

To get this working:

**./build.gradle**
```
dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0-alpha3'
    }
```

**app/build.gradle**
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.0"

    ...
}

dependencies {
    compile 'com.jakewharton:butterknife:8.1.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.1.0'
}
```

**gradle/wrapper/gradle-wrapper.properties**
```
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14-all.zip
```
