### ISSUE TITLE
"Declaration access can be weaker" linting warning on injected member variables

### ISSUE THREAD

**Issue by cemrich** [JakeWharton/butterknife#748]
I get the `Declaration access can be weaker` error from Android lint when analyzing my code. Lint wants me to narrow down the access modifier of my member variables that hold the injected views to `private`:

```
public class FullscreenActivity extends AppCompatActivity {
    protected @BindView(R.id.fullscreen_content) View mContentView;
}
```

Of course I can't change the variable to `private` because it will throw a compiler error: `@BindView fields must not be private or static. (my.package.FullscreenActivity.mContentView)`

I have configured the `android-apt` plugin. Is there anything I can do to avoid both errors/warnings? I don't want to disable all lint warnings of this type or clutter my code with more annotations.

**Comment by JakeWharton** [comment]
There should be way to disable this based on the presence of an annotation for your IDE or tool. In this case, you would want to disable it for anything annotated with a class in `butterknife.*`. If this feature is not supported you should file a feature request for it.

This library (and others like Dagger) _require_ that the fields be visible the package so that the generated code can access them. We have no way of changing that so the only changes that can be made are on the side of the tools.

**Comment by darshanatwal** [comment]
Once you see the Inspection Report right click on specific heading eg,."Declaration access can be weaker" & select Edit Settings.
