### ISSUE TITLE
support for multiple layout

### ISSUE THREAD

**Issue by beiliubei** [JakeWharton/butterknife#754]
The case of I have vertical screen and landscape for one activity.However, In landscape mode, will be less than a vertical screen mode button. So any support for @@BindView add a precondition like @BindView(R.id.login_btn, layout=xxx)

**Comment by xxxzhi** [comment]
I think you can use fragment to realize your purpose. Vertical Fragment is for vertical screen while a   Landscape Fragment is for landscape screen.

**Comment by JakeWharton** [comment]
Butter Knife is a binding library not an inflation library so it knows nothing about how the views got into the view hierarchy. If you have a view that only existing in one configuration you can mark it as `@Nullable` which implies that it's optional. Another technique would be to use two objects with different bindings for each of the two configurations.

Beyond that, there's no way for the library to do any more since it doesn't take part in inflation.
