### ISSUE TITLE
Change README.md

### ISSUE THREAD

**Issue by Sigvent** [JakeWharton/butterknife#798]
Hello @JakeWharton,

I was upgrading the butterknife library from 7.0.1 to 8.4.0 and my Butterknife doesn't work correctly. I searched where the issue is coming. I implemented everything correctly, the code is correct (replace @Bind by @BindView). I put some logs after Butterknife.bind(this) + findViewById() and the butterknife doesn't find the resourceId but the findViewById does it.

I checked my build.gradle and I saw that I copied these follow lines from README.md : 

dependencies {
  compile 'com.jakewharton:butterknife:8.4.0'
  **annotationProcessor** 'com.jakewharton:butterknife-compiler:8.4.0'
}

Instead of these lines from the website :

dependencies {
compile 'com.jakewharton:butterknife:8.4.0'
**apt** 'com.jakewharton:butterknife-compiler:8.4.0'
}

With `apt 'com.jakewharton:butterknife-compiler:8.4.0'` works for me.

Can you correct this ? 
Thanks

**Comment by JakeWharton** [comment]
The README is correct. The website is wrong. I'll update the website. Ensure you're using version 2.2.0 or newer of the Android Gradle plugin.

**Comment by lawloretienne** [comment]
I noticed something very odd.  I also upgraded from version 7.0.1 to version 8.4.0.  And after the call to Butterknife.bind(this) inside an Activity, if i tried to access one of the views that i setup with a @BindView annotation and called a method on this view, the view was null.  Calling findViewById() would return the actual view.

So then i took a look at how i had dependencies set up.  Initially I had 
annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
which seemed to be causing issues.

Then i switched to 
apt 'com.jakewharton:butterknife-compiler:8.4.0'
and things started working as expected (views were non-null)

Then i switched back to 
annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
and somehow things are now working.

It seems very odd and I am posting this because hopefully if someone else is having the same issue they wont be stuck like i was.
