### ISSUE TITLE
Is it possible to use ButterKnife's annotations after the ButterKnife compiler runs?

### ISSUE THREAD

**Issue by Zhuinden** [JakeWharton/butterknife#824]
Realm-Java had an issue where the [annotation processor consumed Realm's annotations](https://github.com/realm/realm-java/blob/master/CHANGELOG.md#enhancements-4) ([PR here](https://github.com/realm/realm-java/pull/3216)), thus not allowing other annotation processors to also be used on Realm annotations (primarily `@RealmClass`).

Does ButterKnife consume annotations with the compiler?

**Comment by Zhuinden** [comment]
I wonder if https://github.com/JakeWharton/butterknife/blob/master/butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java#L192 means it's a no 😭

**Comment by JakeWharton** [comment]
Do you have a use case for processing with Butter Knife's annotations? As far as I know you should _always_ return `false` from `process` implementations.

Butter Knife has been returning true since the [very first commit][1] nearly 4 years ago. I didn't know what I was doing then, of course. Want to send a PR?

 [1]: https://github.com/JakeWharton/butterknife/commit/8b971011893613245ab662450ee6555c30333c7f#diff-f5b25f1587d9715e3a980b11b81850b1R146

**Comment by Zhuinden** [comment]
@JakeWharton technically I had a wild idea the other day, that piggybacking on `@BindView` and `@OnClick` annotations, it'd be possible to generate "espresso page objects" for instrumentation tests.

But I don't know enough at the moment about annotation processors to tell if returning `false` changes anything else beyond allowing other annotation processors to re-use the annotations.

**Comment by Zhuinden** [comment]
Thanks!

Now I have no excuse to write an annotation processor myself :smile:
