### ISSUE TITLE
can't use it with mm

### ISSUE THREAD

**Issue by fenghuilu** [JakeWharton/butterknife#825]
I can't use it while compile my application with cmd 'mm' in android system environment,does it support?
 bellow is my android.mk

LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional

LOCAL_CERTIFICATE := platform

LOCAL_JAVACFLAGS := -processor butterknife.internal.ButterKnifeProcessor

LOCAL_STATIC_JAVA_LIBRARIES := butterknife-annotations\
                               android-support-v7-appcompat

LOCAL_STATIC_JAVA_AAR_LIBRARIES :=butterknife

LOCAL_RESOURCE_DIR := \
        $(LOCAL_PATH)/res \
        frameworks/support/v7/appcompat/res

LOCAL_SRC_FILES := $(call all-java-files-under, src)

LOCAL_PACKAGE_NAME := OnegoButterKnifeDemo

LOCAL_AAPT_FLAGS := \
                    --auto-add-overlay\
                    --extra-packages android.support.v7.appcompat

include $(BUILD_PACKAGE)

include $(CLEAR_VARS)

LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES := butterknife-annotations:libs/butterknife-annotations-8.4.0.jar\
                                        butterknife:libs/butterknife-8.4.0.aar

include $(BUILD_MULTI_PREBUILT)

# Use the following include to make our test apk.
include $(call all-makefiles-under,$(LOCAL_PATH))

**Comment by JakeWharton** [comment]
I have no idea how to use this library with Make. You need to have the 'compiler' and 'annotation' artifacts on javac's processorpath and the 'butterknife' and 'annotations' artifacts on the regular classpath. You'll have to consult people or places where more of those familiar with Make are available to help. Maybe StackOverflow? Since it's not strictly a problem with the library I'm going to close the issue.
