### ISSUE TITLE
Exception :Required view 'forgot_pwd_btn' with ID 2131820812 for method 'onForgotPasswordClick' was not found. If this view is optional add '@Nullable' annotation.

### ISSUE THREAD

**Issue by Sudhanshu2610** [JakeWharton/butterknife#997]
This exception is coming but my my view forgot_pwd_btn is present in the xml 

[LOGINVIEW .docx](https://github.com/JakeWharton/butterknife/files/1110992/LOGINVIEW.docx)

**Comment by Sudhanshu2610** [comment]
Also it is very inconsistent

**Comment by JakeWharton** [comment]
ButterKnife is just calling findViewById and null checking the return value so that view is not present in your hierarchy. You can confirm this by calling findViewById yourself.

If you believe there's a bug in the library then a failing test case or sample project which demonstrates it is the only way to know what behavior you're seeing.
